#!/usr/bin/env node
// Generates backend/src/db/seed.sql with properly bcrypt-hashed demo passwords.
// Run via: make install  (executed automatically — do not run manually)
'use strict';

const bcrypt = require('bcrypt');
const fs = require('fs');
const path = require('path');

const SALT_ROUNDS = 12;

async function main() {
  const [aliceHash, bobHash] = await Promise.all([
    bcrypt.hash('password', SALT_ROUNDS),
    bcrypt.hash('password', SALT_ROUNDS),
  ]);

  const sql = `-- Auto-generated by 'make install' via generate-seed.js. Do not edit manually.
-- Demo credentials:
--   alice@example.com / password
--   bob@example.com  / password

INSERT INTO users (email, password_hash) VALUES
  ('alice@example.com', '${aliceHash}'),
  ('bob@example.com',   '${bobHash}')
ON CONFLICT (email) DO NOTHING;

INSERT INTO trips (user_id, name, destination, start_date, end_date)
SELECT id, 'Thailand 2025', 'Thailand', '2025-03-01', '2025-03-21'
FROM users WHERE email = 'alice@example.com';

INSERT INTO expenses (trip_id, user_id, amount, currency, category, date, notes)
SELECT t.id, u.id, e.amount, e.currency, e.category, e.date::DATE, e.notes
FROM users u
JOIN trips t ON t.user_id = u.id AND t.name = 'Thailand 2025'
CROSS JOIN (VALUES
  (850.00::NUMERIC, 'USD'::CHAR(3), 'transport',     '2025-03-01', 'Return flights Bangkok'),
  (180.00,          'USD',          'accommodation',  '2025-03-02', 'Hotel Bangkok 3 nights'),
  ( 12.50,          'USD',          'food',           '2025-03-02', 'Pad Thai street food'),
  ( 15.00,          'USD',          'activities',     '2025-03-03', 'Grand Palace entry'),
  (  5.00,          'USD',          'transport',      '2025-03-03', 'Tuk-tuk across Bangkok'),
  (  8.00,          'USD',          'food',           '2025-03-04', 'Tom Yum soup lunch'),
  ( 25.00,          'USD',          'transport',      '2025-03-05', 'Overnight train to Chiang Mai'),
  ( 45.00,          'USD',          'accommodation',  '2025-03-06', 'Chiang Mai hostel 2 nights'),
  ( 75.00,          'USD',          'activities',     '2025-03-07', 'Elephant sanctuary half day'),
  ( 20.00,          'USD',          'activities',     '2025-03-08', 'Traditional Thai massage'),
  ( 30.00,          'USD',          'other',          '2025-03-08', 'Night market souvenirs'),
  (200.00,          'USD',          'accommodation',  '2025-03-10', 'Koh Samui beach resort 4 nights'),
  ( 55.00,          'USD',          'activities',     '2025-03-12', 'Snorkeling day tour'),
  ( 18.00,          'USD',          'food',           '2025-03-14', 'Seafood BBQ dinner'),
  ( 22.00,          'USD',          'transport',      '2025-03-15', 'Songthaew to beach village')
) AS e(amount, currency, category, date, notes)
WHERE u.email = 'alice@example.com';
`;

  const outPath = path.join(__dirname, 'seed.sql');
  fs.writeFileSync(outPath, sql, 'utf8');
  process.stdout.write(`seed.sql generated at ${outPath}\n`);
}

main().catch(err => {
  process.stderr.write(`generate-seed failed: ${err.message}\n`);
  process.exit(1);
});
