-- Auto-generated by 'make install' via generate-seed.js. Do not edit manually.
-- Demo credentials:
--   alice@example.com / password  (3 trips: Thailand, Japan, Swiss Alps)
--   bob@example.com  / password   (3 trips: New York, Lisbon & Porto, Iceland)

INSERT INTO users (email, password_hash) VALUES
  ('alice@example.com', '$2b$12$V76X1.HxeDwU5gKbySvoPO7Eplb5r4kDk6thYr4Ib2Z.AOrAzK7Vy'),
  ('bob@example.com',   '$2b$12$tW8eIHKMnEzOGONHU/MM4.x6cokKMfjyk1G8FeqxqfSZigjwfEHaO')
ON CONFLICT (email) DO NOTHING;

INSERT INTO trips (user_id, name, destination, start_date, end_date)
SELECT id, 'Thailand 2025', 'Thailand', '2025-03-01', '2025-03-21'
FROM users WHERE email = 'alice@example.com';

INSERT INTO expenses (trip_id, user_id, amount, currency, category, date, notes)
SELECT t.id, u.id, e.amount, e.currency, e.category, e.date::DATE, e.notes
FROM users u
JOIN trips t ON t.user_id = u.id AND t.name = 'Thailand 2025'
CROSS JOIN (VALUES
  (850.00::NUMERIC, 'USD'::CHAR(3), 'transport', '2025-03-01', 'Return flights Bangkok'),
  (180.00, 'USD', 'accommodation', '2025-03-02', 'Hotel Bangkok 3 nights'),
  (12.50, 'USD', 'food', '2025-03-02', 'Pad Thai street food'),
  (15.00, 'USD', 'activities', '2025-03-03', 'Grand Palace entry'),
  (5.00, 'USD', 'transport', '2025-03-03', 'Tuk-tuk across Bangkok'),
  (8.00, 'USD', 'food', '2025-03-04', 'Tom Yum soup lunch'),
  (25.00, 'USD', 'transport', '2025-03-05', 'Overnight train to Chiang Mai'),
  (45.00, 'USD', 'accommodation', '2025-03-06', 'Chiang Mai hostel 2 nights'),
  (75.00, 'USD', 'activities', '2025-03-07', 'Elephant sanctuary half day'),
  (20.00, 'USD', 'activities', '2025-03-08', 'Traditional Thai massage'),
  (30.00, 'USD', 'other', '2025-03-08', 'Night market souvenirs'),
  (200.00, 'USD', 'accommodation', '2025-03-10', 'Koh Samui beach resort 4 nights'),
  (55.00, 'USD', 'activities', '2025-03-12', 'Snorkeling day tour'),
  (18.00, 'USD', 'food', '2025-03-14', 'Seafood BBQ dinner'),
  (22.00, 'USD', 'transport', '2025-03-15', 'Songthaew to beach village')
) AS e(amount, currency, category, date, notes)
WHERE u.email = 'alice@example.com';

INSERT INTO trips (user_id, name, destination, start_date, end_date)
SELECT id, 'Japan 2024', 'Japan', '2024-03-01', '2024-03-12'
FROM users WHERE email = 'alice@example.com';

INSERT INTO expenses (trip_id, user_id, amount, currency, category, date, notes)
SELECT t.id, u.id, e.amount, e.currency, e.category, e.date::DATE, e.notes
FROM users u
JOIN trips t ON t.user_id = u.id AND t.name = 'Japan 2024'
CROSS JOIN (VALUES
  (950.00::NUMERIC, 'USD'::CHAR(3), 'transport', '2024-03-01', 'Return flights to Tokyo'),
  (65000.00, 'JPY', 'accommodation', '2024-03-01', 'Shinjuku hotel 5 nights'),
  (850.00, 'JPY', 'food', '2024-03-02', 'Ramen Ichiran Shinjuku'),
  (3200.00, 'JPY', 'activities', '2024-03-02', 'teamLab Planets entry'),
  (1200.00, 'JPY', 'food', '2024-03-03', 'Convenience store meals'),
  (3000.00, 'JPY', 'transport', '2024-03-03', 'Suica card top-up Tokyo'),
  (4500.00, 'JPY', 'food', '2024-03-04', 'Tsukiji sushi dinner'),
  (8000.00, 'JPY', 'activities', '2024-03-04', 'Tokyo Disneyland day pass'),
  (550.00, 'JPY', 'food', '2024-03-05', 'Matcha soft serve Harajuku'),
  (13080.00, 'JPY', 'transport', '2024-03-06', 'Shinkansen Tokyo to Kyoto'),
  (45000.00, 'JPY', 'accommodation', '2024-03-06', 'Kyoto ryokan 3 nights Gion'),
  (2000.00, 'JPY', 'activities', '2024-03-07', 'Tea ceremony Gion district'),
  (500.00, 'JPY', 'transport', '2024-03-07', 'Kyoto city bus day pass'),
  (2800.00, 'JPY', 'food', '2024-03-07', 'Nishiki Market street food'),
  (1500.00, 'JPY', 'activities', '2024-03-08', 'Sake brewery tour Fushimi'),
  (12000.00, 'JPY', 'other', '2024-03-09', 'Souvenir shopping Gion'),
  (800.00, 'JPY', 'food', '2024-03-10', 'Wagashi sweets Arashiyama'),
  (3000.00, 'JPY', 'transport', '2024-03-12', 'Limousine bus to Kansai airport')
) AS e(amount, currency, category, date, notes)
WHERE u.email = 'alice@example.com';

INSERT INTO trips (user_id, name, destination, start_date, end_date)
SELECT id, 'Swiss Alps 2023', 'Switzerland', '2023-07-05', '2023-07-14'
FROM users WHERE email = 'alice@example.com';

INSERT INTO expenses (trip_id, user_id, amount, currency, category, date, notes)
SELECT t.id, u.id, e.amount, e.currency, e.category, e.date::DATE, e.notes
FROM users u
JOIN trips t ON t.user_id = u.id AND t.name = 'Swiss Alps 2023'
CROSS JOIN (VALUES
  (780.00::NUMERIC, 'USD'::CHAR(3), 'transport', '2023-07-05', 'Return flights to Zurich'),
  (55.00, 'CHF', 'transport', '2023-07-05', 'ZVV day pass Zurich tram'),
  (320.00, 'CHF', 'accommodation', '2023-07-05', 'Zurich city hotel 2 nights'),
  (45.00, 'CHF', 'food', '2023-07-06', 'Fondue dinner old town Zurich'),
  (25.00, 'CHF', 'activities', '2023-07-06', 'Kunsthaus Zurich museum'),
  (32.00, 'CHF', 'other', '2023-07-06', 'Swiss chocolate assortment'),
  (120.00, 'CHF', 'transport', '2023-07-07', 'Swiss Half-Fare Card'),
  (220.00, 'CHF', 'accommodation', '2023-07-07', 'Interlaken hostel 4 nights'),
  (215.00, 'CHF', 'activities', '2023-07-08', 'Jungfraujoch Top of Europe train'),
  (180.00, 'CHF', 'activities', '2023-07-09', 'Paragliding above Interlaken'),
  (28.00, 'CHF', 'food', '2023-07-09', 'Rosti and local beer lunch'),
  (35.00, 'CHF', 'activities', '2023-07-10', 'Lake Brienz boat cruise'),
  (48.00, 'CHF', 'activities', '2023-07-10', 'Grindelwald cable car First'),
  (62.00, 'CHF', 'food', '2023-07-11', 'Raclette dinner Grindelwald'),
  (40.00, 'CHF', 'other', '2023-07-11', 'Hiking gear rental'),
  (55.00, 'CHF', 'food', '2023-07-12', 'Supermarket and picnic supplies'),
  (30.00, 'CHF', 'transport', '2023-07-14', 'Bus to Zurich airport')
) AS e(amount, currency, category, date, notes)
WHERE u.email = 'alice@example.com';

INSERT INTO trips (user_id, name, destination, start_date, end_date)
SELECT id, 'New York City 2025', 'United States', '2025-01-15', '2025-01-22'
FROM users WHERE email = 'bob@example.com';

INSERT INTO expenses (trip_id, user_id, amount, currency, category, date, notes)
SELECT t.id, u.id, e.amount, e.currency, e.category, e.date::DATE, e.notes
FROM users u
JOIN trips t ON t.user_id = u.id AND t.name = 'New York City 2025'
CROSS JOIN (VALUES
  (620.00::NUMERIC, 'USD'::CHAR(3), 'transport', '2025-01-15', 'Return flights to JFK'),
  (895.00, 'USD', 'accommodation', '2025-01-15', 'Midtown Manhattan hotel 6 nights'),
  (32.00, 'USD', 'transport', '2025-01-15', 'JFK AirTrain and subway pass'),
  (35.00, 'USD', 'food', '2025-01-16', 'Brunch Upper West Side'),
  (45.00, 'USD', 'activities', '2025-01-16', 'MoMA entry'),
  (180.00, 'USD', 'activities', '2025-01-17', 'Broadway show Hamilton'),
  (28.00, 'USD', 'food', '2025-01-17', 'NY pizza slice and cheesecake'),
  (42.00, 'USD', 'food', '2025-01-18', 'Katz Deli pastrami sandwich'),
  (38.00, 'USD', 'activities', '2025-01-18', 'Top of the Rock observation deck'),
  (15.00, 'USD', 'transport', '2025-01-19', 'Weekly MetroCard'),
  (55.00, 'USD', 'food', '2025-01-19', 'Steak dinner Meatpacking District'),
  (65.00, 'USD', 'other', '2025-01-20', 'Shopping SoHo'),
  (25.00, 'USD', 'activities', '2025-01-20', 'Central Park guided tour'),
  (18.00, 'USD', 'food', '2025-01-21', 'Bagel and coffee deli'),
  (22.00, 'USD', 'transport', '2025-01-22', 'Uber to JFK')
) AS e(amount, currency, category, date, notes)
WHERE u.email = 'bob@example.com';

INSERT INTO trips (user_id, name, destination, start_date, end_date)
SELECT id, 'Lisbon & Porto 2024', 'Portugal', '2024-09-08', '2024-09-19'
FROM users WHERE email = 'bob@example.com';

INSERT INTO expenses (trip_id, user_id, amount, currency, category, date, notes)
SELECT t.id, u.id, e.amount, e.currency, e.category, e.date::DATE, e.notes
FROM users u
JOIN trips t ON t.user_id = u.id AND t.name = 'Lisbon & Porto 2024'
CROSS JOIN (VALUES
  (340.00::NUMERIC, 'EUR'::CHAR(3), 'transport', '2024-09-08', 'Return flights to Lisbon'),
  (280.00, 'EUR', 'accommodation', '2024-09-08', 'Alfama Airbnb 5 nights'),
  (12.00, 'EUR', 'food', '2024-09-09', 'Pastel de nata and espresso'),
  (8.00, 'EUR', 'transport', '2024-09-09', 'Tram 28 day pass Lisbon'),
  (28.00, 'EUR', 'food', '2024-09-10', 'Bacalhau dinner Bairro Alto'),
  (15.00, 'EUR', 'activities', '2024-09-10', 'Belem Tower and Jeronimos entry'),
  (18.00, 'EUR', 'activities', '2024-09-11', 'Sintra day trip train and bus'),
  (35.00, 'EUR', 'food', '2024-09-11', 'Seafood lunch Cascais'),
  (45.00, 'EUR', 'transport', '2024-09-13', 'Train Lisbon to Porto'),
  (210.00, 'EUR', 'accommodation', '2024-09-13', 'Porto guesthouse 4 nights'),
  (22.00, 'EUR', 'activities', '2024-09-14', 'Port wine cellar tour Vila Nova de Gaia'),
  (24.00, 'EUR', 'food', '2024-09-14', 'Francesinha sandwich and beer'),
  (85.00, 'EUR', 'activities', '2024-09-15', 'Douro Valley boat and wine tour'),
  (18.00, 'EUR', 'food', '2024-09-16', 'Bifanas and craft beer'),
  (40.00, 'EUR', 'other', '2024-09-17', 'Azulejo tiles and cork souvenirs'),
  (16.00, 'EUR', 'transport', '2024-09-19', 'Metro to Lisbon airport')
) AS e(amount, currency, category, date, notes)
WHERE u.email = 'bob@example.com';

INSERT INTO trips (user_id, name, destination, start_date, end_date)
SELECT id, 'Iceland 2023', 'Iceland', '2023-08-02', '2023-08-11'
FROM users WHERE email = 'bob@example.com';

INSERT INTO expenses (trip_id, user_id, amount, currency, category, date, notes)
SELECT t.id, u.id, e.amount, e.currency, e.category, e.date::DATE, e.notes
FROM users u
JOIN trips t ON t.user_id = u.id AND t.name = 'Iceland 2023'
CROSS JOIN (VALUES
  (890.00::NUMERIC, 'USD'::CHAR(3), 'transport', '2023-08-02', 'Return flights to Reykjavik'),
  (420.00, 'USD', 'transport', '2023-08-02', 'Campervan rental 8 days'),
  (150.00, 'USD', 'accommodation', '2023-08-02', 'Reykjavik hostel 1 night'),
  (75.00, 'USD', 'food', '2023-08-03', 'Lamb soup and skyr tasting'),
  (120.00, 'USD', 'activities', '2023-08-03', 'Golden Circle guided tour'),
  (65.00, 'USD', 'activities', '2023-08-04', 'Blue Lagoon entry and transfer'),
  (85.00, 'USD', 'food', '2023-08-05', 'Campsite groceries and fuel'),
  (145.00, 'USD', 'activities', '2023-08-06', 'Glacier hike Vatnajokull'),
  (30.00, 'USD', 'food', '2023-08-07', 'Hot dog stand and local diner'),
  (95.00, 'USD', 'activities', '2023-08-08', 'Whale watching Husavik'),
  (55.00, 'USD', 'food', '2023-08-08', 'Fish and chips harbour dinner'),
  (40.00, 'USD', 'other', '2023-08-09', 'Icelandic wool sweater'),
  (25.00, 'USD', 'transport', '2023-08-11', 'Bus to Keflavik airport')
) AS e(amount, currency, category, date, notes)
WHERE u.email = 'bob@example.com';
